@echo off
echo Starting Backend...
start cmd /k "cd NeuroFlow_Backend && .\venv\Scripts\activate && python manage.py runserver"

echo Starting UI...
start cmd /k "cd UI && pnpm run dev"

echo Servers are starting...
