# Generated by Django 5.0.2 on 2024-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('sample_data', models.JSONField()),
                ('column_sum_data', models.JSONField()),
            ],
        ),
    ]
